version: '3'

services: 
    proxy:
        image: artemeesenin/proxy
        ports: 
            - "80:80"
            - "443:443"
        depends_on:
            - main
            - gitlab
        links:
            - main
            - gitlab

    main:
        image: artemeesenin/simple-node-message
        container_name:  main
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
            - MESSAGE=hello world

    gitlab:
        image: artemeesenin/simple-node-message
        container_name:  gitlab
        ports: 
            - "3000:3000"
        environment: 
            - PORT=3000
            - MESSAGE=gitlab
